import type { RecipeInput } from "./types";

export const sampleRecipes: (RecipeInput & { isFavorite: boolean })[] = [
  {
    title: "Krémes paradicsomos tészta",
    description: "Egy gyors, melengető ebéd, amiből sosem marad másnapra.",
    category: "Ebéd",
    prepTime: 25,
    servings: 2,
    ingredients: "250 g rigatoni vagy kedvenc tészta\n300 g passzírozott paradicsom\n2 gerezd fokhagyma\n100 ml főzőtejszín\n1 marék friss bazsalikom\nParmezán, olívaolaj, só, bors",
    instructions: "Főzd meg a tésztát bő, sós vízben a csomagoláson leírtak szerint.\nEgy serpenyőben melegíts olívaolajat, és futtasd meg rajta az aprított fokhagymát.\nÖntsd hozzá a paradicsomot és a tejszínt, majd főzd 8–10 percig.\nForgasd össze a tésztával, szórd meg bazsalikommal és parmezánnal.",
    image: "/images/pasta.jpg",
    isFavorite: true,
  },
  {
    title: "Áfonyás reggeli palacsinta",
    description: "Puha, könnyű palacsinta a ráérős reggelekhez.",
    category: "Reggeli",
    prepTime: 20,
    servings: 4,
    ingredients: "200 g liszt\n2 tojás\n250 ml tej\n1 tk sütőpor\n1 ek cukor\n1 marék áfonya\nJuharszirup a tálaláshoz",
    instructions: "Keverd össze a száraz hozzávalókat egy tálban.\nAdd hozzá a tojásokat és a tejet, majd keverd simára a tésztát.\nKözepes lángon, enyhén olajozott serpenyőben süss belőle kisebb palacsintákat.\nTálald friss áfonyával és egy kevés juharsziruppal.",
    image: "/images/pancakes.jpg",
    isFavorite: false,
  },
  {
    title: "Selymes sütőtökkrémleves",
    description: "Az ősz kedvenc íze egyetlen tálban.",
    category: "Ebéd",
    prepTime: 40,
    servings: 4,
    ingredients: "1 közepes sütőtök\n1 fej vöröshagyma\n2 gerezd fokhagyma\n700 ml zöldségalaplé\n100 ml tejszín\nSó, bors, szerecsendió\nPirított tökmag a tetejére",
    instructions: "A sütőtököt kockázd fel, a hagymát aprítsd finomra.\nKevés olajon párold meg a hagymát és a fokhagymát, majd add hozzá a tököt.\nÖntsd fel az alaplével, és főzd puhára körülbelül 25 perc alatt.\nTurmixold krémesre, keverd bele a tejszínt, majd ízesítsd és tálald tökmaggal.",
    image: "/images/soup.jpg",
    isFavorite: false,
  },
  {
    title: "Nyári bogyós saláta",
    description: "Friss, színes és pont olyan könnyű, amilyennek szeretjük.",
    category: "Vacsora",
    prepTime: 15,
    servings: 2,
    ingredients: "2 marék bébispenót\n100 g eper\n1 marék áfonya\n80 g feta sajt\n2 ek dió\nOlívaolaj és balzsamecet",
    instructions: "Mosd meg a gyümölcsöket és a salátaleveleket.\nAz epret szeleteld fel, a fetát morzsold kisebb darabokra.\nRendezd el a hozzávalókat egy nagy tálban.\nLocsold meg olívaolajjal és balzsamecettel közvetlenül tálalás előtt.",
    image: "/images/salad.jpg",
    isFavorite: false,
  },
  {
    title: "Házi lasagne",
    description: "Rétegekbe bújtatott, igazi családi kedvenc.",
    category: "Ebéd",
    prepTime: 75,
    servings: 6,
    ingredients: "12 lap lasagne tészta\n500 g darált hús\n500 ml paradicsomszósz\n1 fej vöröshagyma\n400 ml besamelmártás\n150 g reszelt sajt\nSó, bors, oregánó",
    instructions: "Pirítsd meg az aprított hagymát és a darált húst, majd add hozzá a paradicsomszószt és a fűszereket.\nEgy sütőtálba rétegezd a ragut, a tésztalapokat és a besamelt.\nA tetejét szórd meg reszelt sajttal.\n180 fokra előmelegített sütőben süsd 35–40 percig, majd szeletelés előtt pihentesd.",
    image: "/images/lasagna.jpg",
    isFavorite: true,
  },
  {
    title: "Puha csokis keksz",
    description: "Ropogós szélek, puha közép, sok-sok csoki.",
    category: "Desszert",
    prepTime: 30,
    servings: 12,
    ingredients: "180 g liszt\n110 g vaj\n100 g barna cukor\n1 tojás\n120 g étcsokoládé\n1/2 tk szódabikarbóna\n1 csipet só",
    instructions: "A puha vajat keverd habosra a cukorral, majd add hozzá a tojást.\nForgasd bele a lisztet, a szódabikarbónát, a sót és az aprított csokoládét.\nFormázz golyókat a tésztából, és helyezd sütőpapírral bélelt tepsire.\n180 fokon süsd 10–12 percig. A tepsin hagyd kihűlni, hogy megmaradjon a puha közepe.",
    image: "/images/cookies.jpg",
    isFavorite: false,
  },
];
